### ISSUE TITLE
第一次运行run.py时无法连接huggingface.co下载open_clip

### ISSUE THREAD

**Issue by kiddoray** [xx025/stable-video-diffusion-webui#10]
你好，我在第一次运行run.py时每次都会报错network is unreachable，下载不了open_clip。将setting.py中的
# environ['http_proxy'] = 'http://127.0.0.1:7890/'
# os.environ['https_proxy'] = 'http://127.0.0.1:7890/'
取消注释后会报错拒绝访问。
我现在直接在本地下载了open_clip_pytorch_model.bin这个文件，请问要放到哪个目录下面哇。
或者如何解决无法连接huggingface的问题
谢谢！

**Comment by xx025** [comment]
看一下wiki上的文档，配置好代理才可以用代理


clip模型的下载具体细节，我也不清楚
