### ISSUE TITLE
使用CG客户端下载镜像到本地运行，默认运行时吃满了CPU，GPU基本没变化

### ISSUE THREAD

**Issue by summeliwod** [xx025/stable-video-diffusion-webui#4]
请问该如何切换到GPU运行呢，或者我该提供些什么更多的信息。

**Comment by xx025** [comment]
https://github.com/xx025/stable-video-diffusion-webui/blob/bb35fe6cf2a5f9d0ff2c8614ae7379348914fd5b/setting.py#L9-L11

设置这个试试

**Comment by xx025** [comment]
要是你就一张卡，标号设置为0

**Comment by summeliwod** [comment]
可以了，谢谢
