### ISSUE TITLE
多nv卡的情况可以通过配置来提升生成的总帧数么

### ISSUE THREAD

**Issue by summeliwod** [xx025/stable-video-diffusion-webui#5]
因为如果只是修改frame的参数会导致内存溢出。所以想请教下两张或多张nv卡的情况是否有办法可以提升显存大小

**Comment by xx025** [comment]
多卡显存累加这个问题太难了，


最简单的就是，换租卡平台上的大卡，也可以试试我部署的，我限制了分辨率最大960，但是显存比较大

**Comment by xx025** [comment]
这个问题，比较难；；

好像这个帧数是没法调整的参数；

至于显存这个事，你可以试试我部署的，显存48G ，不过我限制了分辨率在最高和宽在960px以内
