### ISSUE TITLE
SVD vs AnimateDiff

### ISSUE THREAD

**Issue by christopherquenneville** [xx025/stable-video-diffusion-webui#6]
Hello,

First of all, thank you for making this. Espacially since it's made in Gradio.

A lot of people want to mess around with SVD and this is simpler to work with.

I'd like to ask you if you compared generation results with AnimateDiff (and Deforum) for quality or other aspects.

Thanks,
Good day

**Comment by xx025** [comment]
Em.. , i  just a beginner. The code almost from [URL](https://github.com/mkshing/notebooks/blob/main/stable_video_diffusion_img2vid.ipynb). so I  not compared it to other image generation models.
