### ISSUE TITLE
问题

### ISSUE THREAD

**Issue by arcdodo** [xx025/stable-video-diffusion-webui#9]
每次跑跑就没内存了，怎么储存到数据盘而不是系统盘当中

**Comment by xx025** [comment]
存储 可以 在 setting.py 更改输出路径

 https://github.com/xx025/stable-video-diffusion-webui/blob/20b20233d4a4699b8e96e5c5d6aa31a168468d1c/setting.py#L62-L65

但是目前内存，存在内存泄漏的问题，建议设置定时任务定时重启

如果你可以解决内存泄漏问题，欢迎提个pr
